name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rust tool chain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: x86_64-unknown-linux-musl

      - name: Install required tools
        run: sudo apt update && sudo apt install musl-tools -y

      - name: Lint the code
        run: cargo clippy

      - name: Run the security audit check, ignoring known issue that is not relevant for this project
        run: cargo audit

      - name: Run the tests with the static target for the debug build
        run: cargo test --target x86_64-unknown-linux-musl
